# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96c22e228497d8f014e93e3016ebce3dbc771b19c02c257c9d4c4dd4a7777b3a3af09a6c11151602ad4be654ffba65b6bf2249be556da0a5272392460319309e

test:
  secret_key_base: ac12cad3c0342d5166613c23efebf7aaa06545378251532759001f0eb8c7af556ed032eda3662ff2ee89efb555b8fab5816d975753afe2e522af417885333848

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
